services:
  uds-server-0:
    build: .
    restart: 'unless-stopped'
    command:
      - local
      - can0
    network_mode: host
    cpus: 1
    mem_limit: 1G

  uds-server-1:
    build: .
    restart: 'unless-stopped'
    command:
      - local
      - can1
    network_mode: host
    cpus: 1
    mem_limit: 1G

  uds-server-2:
    build: .
    restart: 'unless-stopped'
    command:
      - local
      - can2
    network_mode: host
    cpus: 1
    mem_limit: 1G

  uds-server-3:
    build: .
    restart: 'unless-stopped'
    command:
      - local
      - can3
    network_mode: host
    cpus: 1
    mem_limit: 1G
