services:
  uds-server-0:
    build: .
    restart: 'unless-stopped'
    command:
      - local
      - can0
    environment:
      - FLAG=CHV{m4mm4_m14!_1_5h0uld-4_c4lL_m4r10_t0_f1x-4_7h15!}
    network_mode: host
    cpus: 1
    mem_limit: 1G

  uds-server-1:
    build: .
    restart: 'unless-stopped'
    command:
      - local
      - can1
    environment:
      - FLAG=CHV{m4mm4_m14!_1_5h0uld-4_c4lL_m4r10_t0_f1x-4_7h15!}
    network_mode: host
    cpus: 1
    mem_limit: 1G

  uds-server-2:
    build: .
    restart: 'unless-stopped'
    command:
      - local
      - can2
    environment:
      - FLAG=CHV{m4mm4_m14!_1_5h0uld-4_c4lL_m4r10_t0_f1x-4_7h15!}
    network_mode: host
    cpus: 1
    mem_limit: 1G

  uds-server-3:
    build: .
    restart: 'unless-stopped'
    command:
      - local
      - can3
    environment:
      - FLAG=CHV{m4mm4_m14!_1_5h0uld-4_c4lL_m4r10_t0_f1x-4_7h15!}
    network_mode: host
    cpus: 1
    mem_limit: 1G
